pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240222151441/TBAtest_backport_report_as_comment/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20240222151441/TBAtest_backport_report_as_comment/stable/#3.1
      labels:
      - backported
      report_as_comment: true
  conditions:
  - base=20240222151441/TBAtest_backport_report_as_comment/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
