pull_request_rules:
- actions:
    queue:
      name: default
      update_method: merge
  conditions:
  - base=20230928092822/test_queue_bot_update_with_update_method_merge/main
  - label=queue
  name: merge default
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
