partition_rules:
- conditions: []
  fallback_partition: true
  name: fallback_partition
- conditions:
  - files~=^projA/
  name: projA
- conditions:
  - files~=^projB/
  name: projB
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230426160534/test_fallback_partition_reset_when_pr_manual_merge_dont_match_any_partitions/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: true
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
