pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20240117102614/test_duplicate_pr/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - base=20240117102614/test_duplicate_pr/main
  - check-success=continuous-integration/fake-ci
  name: foo
