pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230717123731/test_unsuccessful_checks_failed_with_toto/main
  - label=queue
  name: merge default
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  - status-success=continuous-integration/fake-ci_2
  - status-success=continuous-integration/fake-ci_3
  name: default
  speculative_checks: 3
