pull_request_rules:
- actions:
    queue:
      merge_bot_account: mergify-test1
      name: default
  conditions:
  - base=20231115161413/test_queue_without_branch_protection_for_queueing_conf_in_queue_rules/main
  - label=queue
  name: Merge priority high
queue_rules:
- branch_protection_injection_mode: none
  conditions: []
  merge_method: squash
  name: default
