pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20220825144446/test_draft_pr_unqueue_after_unexpected_changes/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
