pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20221214095902/test_merge_priority_deprecation_notice/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
