pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240226153701/TBAtest_backport_report_mode_comment/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20240226153701/TBAtest_backport_report_mode_comment/stable/#3.1
      labels:
      - backported
      report_mode:
      - check
      - comment
  conditions:
  - base=20240226153701/TBAtest_backport_report_mode_comment/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
