extends: functional-testing-repo-Syffe2

queue_rules:
  - name: default
    merge_conditions:
      - "#approved-reviews-by>=2"

pull_request_rules:
  - name: queue default
    conditions:
      - label!=toto
    actions:
      queue:
        name: default
