pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230509154148/test_queue_with_two_pull_request_rules_that_match_then_unmatch/main
  - label=toto
  name: merge high
- actions:
    queue:
      name: default
  conditions:
  - base=20230509154148/test_queue_with_two_pull_request_rules_that_match_then_unmatch/main
  - label=tutu
  name: merge low
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
