pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20240111101234/test_disallowed_change_mergify_yml/main
  mergify_configuration_changed: false
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
