pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221221150630/test_queue_priority_rules/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  priority_rules:
  - conditions:
    - label=hotfix
    name: hotfix PR detected
    priority: high
  - conditions:
    - -label=hotfix
    name: default priority
    priority: medium
