pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230220091400/test_queue_routing_conditions_success/main
  - label=queue
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  routing_conditions:
  - files~=^test/
