pull_request_rules:
- actions:
    copy:
      branches:
      - 20240318103920/test_copy_with_commit_signature/dev
  conditions:
  - base=20240318103920/test_copy_with_commit_signature/main
  - label=backport-#3.1
  name: copy
