pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230614094910/test_pr_with_depends_on_unqueued_after_dependent_pr_failed_to_merge_no_inplace/main
  - label=queue
  name: default merge
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  draft_bot_account: mergify-test4
  name: default
  speculative_checks: 5
