pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230828153011/test_error_bypass_branch_protections_with_off_injection_mode_without_bot_account/main
  - label=queue
  name: Merge default
queue_rules:
- branch_protection_injection_mode: 'off'
  merge_conditions: []
  name: default
