pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230322134504/test_queued_label_rule_after_config_update/main
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
