pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20240111080415/test_disallowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
