pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20230111092626/test_review_template/main
  name: approve
- actions:
    review:
      message: WTF {{author}}?
      type: REQUEST_CHANGES
  conditions:
  - base=20230111092626/test_review_template/main
  - '#approved-reviews-by>=1'
  name: requested
