pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20231121104710/test_queue_inplace_interrupted/main
  - label=queue
  name: Merge priority high
queue_rules:
- conditions: []
  name: default
  require_branch_protection: false
