pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240227111640/TBAtest_backport_report_mode_check_only/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20240227111640/TBAtest_backport_report_mode_check_only/stable/#3.1
      labels:
      - backported
  conditions:
  - base=20240227111640/TBAtest_backport_report_mode_check_only/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
