pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230321170413/test_queued_label/main
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
