pull_request_rules:
- actions:
    queue:
      name: new_default
  conditions:
  - base=20221025141549/test_unexpected_config_change/main
  - label=queue
  name: Merge me
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: new_default
