pull_request_rules:
- actions:
    merge:
      mergify_configuration_changed: false
  conditions:
  - base=20240111101922/test_disallowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
