pull_request_rules:
- actions:
    merge:
      priority: high
  conditions:
  - base=20221213162000/test_priority_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
