pull_request_rules:
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: caca
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
