partition_rules:
- fallback_partition: true
  name: fallback_partition
- conditions:
  - files~=^projA/
  name: projA
- conditions:
  - files~=^projB/
  name: projB
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230525151954/test_fallback_partition_report_after_manual_merge/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: true
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
