pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230726134735/test_unsuccessful_checks_failed_with_all_types_of_conditions/main
  - label=queue
  name: merge default
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci_2
  - status-success=continuous-integration/fake-ci_3
  name: default
  queue_conditions:
  - status-success=continuous-integration/fake-ci
