pull_request_rules:
- actions:
    queue:
      name: urgent
  conditions:
  - base=20220214145201/test_queue_isolation/main
  - label=queue-urgent
  name: Merge priority high
- actions:
    queue:
      name: default
  conditions:
  - base=20220214145201/test_queue_isolation/main
  - label=queue
  name: Merge default
- actions:
    queue:
      name: low-priority
  conditions:
  - base=20220214145201/test_queue_isolation/main
  - label=queue-low
  name: Merge low
queue_rules:
- conditions:
  - status-success=continuous-integration/fast-ci
  name: urgent
  speculative_checks: 5
- conditions:
  - status-success=continuous-integration/slow-ci
  name: default
  speculative_checks: 5
- conditions:
  - status-success=continuous-integration/slow-ci
  name: low-priority
  speculative_checks: 5
