queue_rules:
  - name: default
    conditions:
      - check-success=compile-and-test

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=compile-and-test
    actions:
      queue:
        name: default
