pull_request_rules:
- actions:
    queue:
      name: default
  caca:
  - base=20230322104427/test_invalid_configuration_fixed_by_pull_request/main
  name: Queue
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
