pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230905154110/test_test_batch_max_failure_resolution/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: false
  batch_max_failure_resolution_attempts: 0
  batch_size: 3
  checks_timeout: 10 m
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  speculative_checks: 2
