pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240221140012/TBAtest_backport_report_result_comment/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20240221140012/TBAtest_backport_report_result_comment/stable/#3.1
      labels:
      - backported
      report_result: true
  conditions:
  - base=20240221140012/TBAtest_backport_report_result_comment/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
