pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20230613122352/test_backport_with_change_already_in_destination_branch/stable/#3.1
  - label=merge test branch
  name: Merge on test branch
- actions:
    merge:
      method: merge
  conditions:
  - base=20230613122352/test_backport_with_change_already_in_destination_branch/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20230613122352/test_backport_with_change_already_in_destination_branch/stable/#3.1
  conditions:
  - base=20230613122352/test_backport_with_change_already_in_destination_branch/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
