pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20231120162616/test_queue_inplace_interrupted/main
  - label=queue
  name: Merge priority high
queue_rules:
- branch_protection_injection_mode: merge
  conditions: []
  name: default
