pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20220701100504/test_failed_base_changeable_attributes_rules_in_not_applicable_summary_section_with_complex_conditions/main
  name: approved review
- actions:
    merge:
      method: rebase
  conditions:
  - base=20220701100504/test_failed_base_changeable_attributes_rules_in_not_applicable_summary_section_with_complex_conditions/main
  - '#approved-reviews-by>=1#changes-requested-reviews-by=0#review-threads-unresolved=0label!=work-in-progresslabel!=manual
    mergestatus-success=continuous-integration/fake-ci'
  name: valid rule base
