pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230126151047/test_queue_routing_conditions_failure_update_after_queued/main
  - label=queue
  name: Queue
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  routing_conditions:
  - label=routing
