pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=dummy
  name: valid PR dummy
- actions:
    merge:
      method: rebase
  conditions:
  - base=20220629152308/test_failed_special_attributes_rules_in_not_applicable_summary_section/main
  name: valid PR main
