pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20221214160106/test_rebase_fallback_deprecation_notice_not_present_in_summary/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
