partition_rules:
- conditions:
  - files~=^projA/
  name: projA
- conditions:
  - files~=^projB/
  name: projB
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230417100750/test_reset_all_partitions_when_pr_is_manually_merged_and_code_dont_match_any_partition/main
  - label=queue
  name: Automatic merge
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
