pull_request_rules:
- actions:
    merge:
      mergify_configuration_change: false
  conditions:
  - base=20240111102119/test_disallowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
