pull_request_rules:
- actions:
    queue:
      merge_bot_account: mergify-test4
      name: default
  conditions:
  - base=20231113145707/test_merge_without_admin_bot_account/main
  - label=queue
  name: Merge default
queue_rules:
- branch_protection_injection_mode: none
  merge_conditions: []
  name: default
