pull_request_rules:
- actions:
    request_reviews:
      teams:
      - mergifyio-testing/BOT
  conditions:
  - base=20240124184735/test_request_reviews_teams_with_organization/main
  name: request_reviews
