pull_request_rules:
- actions:
    review:
      type: APPROVE
  conditions:
  - base=20220701095919/test_failed_base_changeable_attributes_rules_in_not_applicable_summary_section_with_complex_conditions/main
  name: approved review
- actions:
    merge:
      method: rebase
  conditions:
  - base=20220701095919/test_failed_base_changeable_attributes_rules_in_not_applicable_summary_section_with_complex_conditions/main
  - label!=work-in-progresslabel!=manual mergestatus-success=continuous-integration/fake-ci
  name: valid rule base
