pull_request_rules:
- actions:
    queue:
      merge_bot_account: mergify-test1
      merge_method: squash
      name: default
  conditions:
  - base=20231115160800/test_queue_without_branch_protection_for_queueing/main
  - label=queue
  name: Merge priority high
queue_rules:
- branch_protection_injection_mode: none
  conditions: []
  name: default
