pull_request_rules:
- actions:
    merge:
      method: merge
  conditions:
  - base=20240227160120/TBAtest_backport_report_mode_error/main
  - label=backport-#3.1
  name: Merge on main
- actions:
    backport:
      branches:
      - 20240227160120/TBAtest_backport_report_mode_error/stable/#3.1
      labels:
      - backported
      report_mode: []
  conditions:
  - base=20240227160120/TBAtest_backport_report_mode_error/main
  - label=backport-#3.1
  name: Backport to stable/#3.1
