pull_request_rules:
- actions:
    queue: {}
  conditions:
  - base=20221214103602/test_rebase_fallback_deprecation_notice_queue/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
