pull_request_rules:
- actions:
    merge: {}
  conditions:
  - base=20240124145550/test_allowed_change_mergify_yml/main
  name: nothing
- actions:
    merge: {}
  conditions:
  - label!=wip
  name: foobar
