pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230727133910/test_unsuccessful_checks_failed_with_pull_request_rules/main
  - label=queue
  - status-success=continuous-integration/fake-ci
  name: merge default
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci_2
  - status-success=continuous-integration/fake-ci_3
  name: default
  queue_conditions:
  - status-success=continuous-integration/fake-ci_4
