pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221021145710/test_toto/main
  - label=queue
  name: Merge priority high
queue_rules:
- batch_size: 2
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
