pull_request_rules:
- actions:
    merge:
      rebase_fallback: null
  conditions:
  - base=20221214103809/test_rebase_fallback_deprecation_notice/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
