pull_request_rules:
- actions:
    update: {}
  conditions:
  - base=20231208204147/test_update_action_on_conflict/main
  name: update
- actions:
    merge: {}
  conditions:
  - base=20231208204147/test_update_action_on_conflict/main
  - label=merge
  name: merge
