pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230509131058/test_queue_with_bot_account/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: false
  conditions:
  - status-success=continuous-integration/fake-ci
  draft_bot_account: mergify-test4
  name: default
  priority_rules:
  - conditions:
    - label=hotfix
    name: hotfix PR detected
    priority: high
  speculative_checks: 5
