pull_request_rules:
- actions:
    comment:
      bot_account: '{{ body }}'
      message: WTF?
  conditions:
  - base=20240124150037/test_deprecated_multiple_rules_with_same_name/main
  name: comment
- actions:
    comment:
      bot_account: '{{ body }}'
      message: Ola quetal?
  conditions:
  - base=20240124150037/test_deprecated_multiple_rules_with_same_name/main
  name: comment
