pull_request_rules:
- actions:
    merge:
      rebase_fallback: merge
  conditions:
  - base=20221213164007/test_rebase_fallback_brownout/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
