pull_request_rules:
- actions:
    queue:
      name: foo
  conditions:
  - base=20230316171633/test_get_pull_request_summary/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - base=20230316171633/test_get_pull_request_summary/main
  - check-success=continuous-integration/fake-ci
  name: foo
