pull_request_rules:
- actions:
    merge:
      commit_message_template: '{{ title }} (#{{ number }})

        {{body}}

        superRP!

        '
  conditions:
  - base=20240109101027/test_merge_template/main
  name: merge on main
