pull_request_rules:
- actions:
    queue: ''
  conditions:
  - base=20240117100510/test_pull_request_implicitly_merged/main
  name: default merge
queue_rules:
- name: default
  priority_rules:
  - conditions:
    - label=urgent
    name: high priority
    priority: high
