pull_request_rules:
- actions:
    queue:
      merge_bot_account: mergify-syffe
      name: default
  conditions:
  - base=20230828133533/test_bypass_branch_protections_with_off_injection_mode/main
  - label=queue
  name: Merge default
queue_rules:
- branch_protection_injection_mode: 'off'
  merge_conditions: []
  name: default
