pull_request_rules:
- actions:
    dismiss_reviews:
      approved: true
      changes_requested:
      - mergify-test1
      message: '{{Loser'
  conditions:
  - base=20240124180732/test_dismiss_reviews_custom_message_syntax_error/main
  name: dismiss reviews
