pull_request_rules:
- actions:
    queue:
      name: urgent
  conditions:
  - base=20221010162757/test_queue_freeze_with_pr_just_about_to_merge/main
  - label=queue-urgent
  name: Merge priority high
- actions:
    queue:
      name: default
  conditions:
  - base=20221010162757/test_queue_freeze_with_pr_just_about_to_merge/main
  - label=queue
  name: Merge default
- actions:
    queue:
      name: low
  conditions:
  - base=20221010162757/test_queue_freeze_with_pr_just_about_to_merge/main
  - label=low-queue
  name: Merge low
queue_rules:
- conditions: []
  name: urgent
- conditions:
  - status-success=continuous-integration/default-ci
  name: default
- conditions:
  - status-success=continuous-integration/low-ci
  name: low
