pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230825145123/test_bypass_branch_protections_with_off_injection_mode/main
  - label=queue
  name: Merge default
queue_rules:
- merge_conditions: []
  name: default
  require_branch_protection: false
