pull_request_rules:
- actions:
    merge:
      priority: high
  conditions:
  - base=20221214160734/test_merge_priority_deprecation_notice_not_present_in_summary/main
  - label=high
  - status-success=continuous-integration/fake-ci
  name: Merge priority high
