pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=20221223131008/test_toto/main
  - '#approved-reviews-by>=2'
  - status-success=ci/myfavoriteci
  name: automatic merge
- actions:
    queue:
      name: default
  conditions:
  - base=20221223131008/test_toto/main
  - label=queue
  name: automatic queue
queue_rules:
- conditions:
  - status-success=ci/myfavoriteci
  - schedule=Mon-Fri 09:00-17:30[UTC]
  name: default
