pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230126155448/test_queue_routing_conditions_failure/main
  - label=queue
  name: Queue
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  routing_conditions:
  - files~=^dummy/
