partition_rules:
- fallback_partition: true
  name: fallback_partition
- conditions:
  - files~=^projA/
  name: projA
- conditions:
  - files~=^projB/
  name: projB
pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240117232334/test_partition_reset_when_pr_manual_merge_matches_one_partition/main
  - label=queue
  name: Automatic merge
queue_rules:
- merge_conditions:
  - status-success=continuous-integration/fake-ci
  name: default
