pull_request_rules:
- actions:
    merge:
      method: rebase
  conditions:
  - base=dummy
  name: valid PR dummy
- actions:
    merge:
      method: rebase
  conditions:
  - or:
    - label=test
    - base=dummy
  name: valid PR main
