pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240117113203/test_queue_just_rebase/main
  - label=queue
  name: default merge
queue_rules:
- conditions:
  - label=queue
  name: default
