pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20240325161410/test_delayed_refresh_event_has_received_at_attribute/main
  - label=queue
  name: queue
queue_rules:
- allow_inplace_checks: false
  merge_conditions:
  - schedule=09:00-18:00
  - check-success=continuous-integration/fake-ci
  name: default
