pull_request_rules:
- actions:
    queue:
      name: default
      update_bot_account: mergify-test1
      update_method: merge
  conditions:
  - base=20231002162452/test_queue_bot_update_with_update_method_merge/main
  - label=queue
  name: merge default
queue_rules:
- conditions:
  - status-success=continuous-integration/fake-ci
  name: default
