pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20221226154545/test_train_reset_after_pr_unexpected_updated_changes/main
  - label=queue
  name: Merge priority high
queue_rules:
- allow_inplace_checks: true
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
