pull_request_rules:
- actions:
    queue:
      name: default
  conditions:
  - base=20230123161449/test_queue_routing_conditions_failure_update_after_queued/main
  - label=queue
  name: Queue
queue_rules:
- allow_inplace_checks: true
  batch_max_wait_time: 0 s
  batch_size: 3
  conditions:
  - status-success=continuous-integration/fake-ci
  name: default
  routing_conditions:
  - files~=^test/
  speculative_checks: 2
